name: "\U0001F680 New feature proposal"
description: Propose a new feature
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a feature request! Please fill out this form as completely as possible.
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature you'd like to request
      description: A clear and concise description of what you want and what your use case is.
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [docs](https://github.com/FatehAK/vite-plugin-image-optimizer#readme).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/FatehAK/vite-plugin-image-optimizer/issues) that requests the same feature to avoid creating a duplicate.
          required: true
